### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by mfeif** [wxl/blogofobe#9]
I'm running from the current git tip; trying to follow instructions from 

`http://blogofile.readthedocs.org/en/latest/quick_setup.html`

When I do `blogofobe build -s ./` I get:

```
ERROR:blogofobe:Fatal build error occured, calling bf.config.build_exception()
Traceback (most recent call last):
  File "/Users/mjf/venv/mf.com_site/bin/blogofobe", line 9, in <module>
    load_entry_point('blogofobe==0.8b1', 'console_scripts', 'blogofobe')()
  File "/Users/mjf/Dropbox/current.dev/blogofobe/blogofobe/main.py", line 58, in main
    args.func(args)
  File "/Users/mjf/Dropbox/current.dev/blogofobe/blogofobe/main.py", line 388, in do_build
    writer.write_site()
  File "/Users/mjf/Dropbox/current.dev/blogofobe/blogofobe/writer.py", line 49, in write_site
    self.__run_controllers()
  File "/Users/mjf/Dropbox/current.dev/blogofobe/blogofobe/writer.py", line 162, in __run_controllers
    controller.run_all(namespaces)
  File "/Users/mjf/Dropbox/current.dev/blogofobe/blogofobe/controller.py", line 229, in run_all
    c.mod.run()
  File "/Users/mjf/Dropbox/current.dev/blogofobe_blog/blogofobe_blog/site_src/_controllers/blog/__init__.py", line 89, in run
    tags.sort_into_categories()
NameError: global name 'tags' is not defined
```

**Comment by mfeif** [comment]
It seems that "tags" is never imported in that file; I added it, and fixed the typo from 

`tags.sort_into_categories()` to `tags.sort_into_tags()` which was in tags.py...

And I got another traceback :-(

```
  File "base_mako", line 21, in render_body
  File "site_mako", line 37, in render_body
  File "permapage_mako", line 33, in render_body
  File "/Users/mjf/venv/mf.com_site/lib/python2.7/site-packages/Mako-1.0.1-py2.7.egg/mako/runtime.py", line 730, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "post_mako", line 42, in render_body
AttributeError: 'str' object has no attribute 'path'
```

**Comment by mfeif** [comment]
I think this was due to incomplete build originally, after I fixed the other bug, I seem to be able to build.

Relevant pull request (over at _blog where this should have been):

`https://github.com/wxl/blogofobe_blog/pull/1`
